# Default configuration for Example service controller
#
# Author: Peter K. Lee (peter@corenova.com)
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0

example-service:controller:
  name: example-service-controller
  description: |
    The Example Service Controller for CORD

  view-url: 'http://some-url'
  icon-url: 'http://some-url'

yang-openapi:info:
  title: Example Service Controller
  description: |
    YANG model-driven Example Service Controller for CORD

  version: '1.0'
  contact:
    name: Peter Lee
    url: 'http://github.com/corenova/yang-cord'
    email: peter@corenova.com
  license:
    name: 'Apache-2.0'
