# Sample initial configuration for testing XOS/CORD
#
# Author: Peter K. Lee (peter@corenova.com)
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0

# Test configuration for CORD Subscribers
xos-controller:tenant:
  cord-tenant:cord:
    subscriber:
      - id: 1
      - id: 2
      - id: 3
      - id: 4
      - id: 5

# Test configuration for Slice  
xos-controller:core:
  xos-slice:slice:
    - id: 1
      name: Test Slice for VSG
      policy:
        max-instances:  10
        default-flavor: 10
        default-image:  20

# Test configuration for emulating virtualized infrastructure
opnfv-iaas:controller:
  compute:
    flavor:
      - id: 10
        name: small
        disk: 1
        ram: 512
        vcpus: 1
      - id: 11
        name: medium
        disk: 10
        ram: 1024
        vcpus: 2
      - id: 12
        name: large
        disk: 50
        ram: 4096
        vcpus: 4
    image:
      - id: 20
        name: A sample VSG image
        checksum: some-checksum
        size: 121313
        container: bare
        disk: raw
        content: '/some/file/location'

# This configuration models two separate ONU/ONT endpoint links
# (subscribers) connected to a single OLT device.
cord-volt-service:controller:
  id: 1000
  name: demo-volt-controller
  description: |
    This is a sample demo VOLT controller with mock data
  
  view-url: 'http://some-url-to-volt'
  icon-url: 'http://some-url-to-volt.icon'

  # list of OLT devices
  device: 
    - name: Mock OLT Device
      mac: 6c:b0:ce:fb:b1:39
      uplink:
        network: 02e6e31a-93f7-48ac-ac41-a043558ae446
        tag: 222
      link: # list of ONU connections to this OLT device
        - serial: some-unique-onu-1
          mac: 6c:b0:ce:fb:b1:40
          active: true
          tag: 432
        - serial: some-unique-onu-2
          mac: ff:b0:ce:fb:b1:40
          active: true
          tag: 450

  # VOLT agent aggregates ONU connections to a big switch abstraction
  port: 
    - id: 605faceb-f5af-4e6d-b205-b67c5ddbc582
      link: some-unique-onu-1
    - id: 0293a880-38a0-4cbe-b737-30b4202d522e
      link: some-unique-onu-2

  # list of unique VOLT subscribers
  subscriber: 
    - id: 1
      tags:
        outer: 222
        inner: 432
      outflow: 605faceb-f5af-4e6d-b205-b67c5ddbc582
    - id: 2
      tags:
        outer: 222
        inner: 450
      outflow: 0293a880-38a0-4cbe-b737-30b4202d522e

cord-vsg-service:controller:
  id: 2000
  name: demo-vsg-controller
  description: |
    This is a sample demo VSG controller with mock data

  view-url: 'http://some-url-to-vsg'
  icon-url: 'http://some-url-to-vsg.icon'

  slice: 
    id: 1
    name: Test Slice for VSG
    policy:
      max-instances:  10
      default-flavor: 10
      default-image:  20

  gateway:
    - id: 1212
      features:
        firewall:
          enabled: true
        url-filter:
          enabled: true
      uplink:
        network: 
        port: 
      flow:

  # list of unique VSG subscribers
  subscriber:
    - id: 1
      inflow: 605faceb-f5af-4e6d-b205-b67c5ddbc582
      outflow: 
      
